services:
  db:
    container_name: stockmanagement
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 112233
      POSTGRES_DB: stockmanagement
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
